### ISSUE TITLE
update setuptools required version?

### ISSUE THREAD

**Issue by jhgit** [twisted/incremental#122]
Trying to build incremental 24.7.2 with setuptools 63.1.0 and python 3.8 (not EOL when I found this) or python 3.9 (not EOL until 2025-10) gives an error (below).

pyproject.toml has:

    requires = [
        # Keep this aligned with the project dependencies.
        "setuptools >= 61.0",
        "tomli; python_version < '3.11'",
    ]

Maybe that setuptools requirement specification needs to be updated.  It seems to build okay with setuptools 63.1.0 when using python 3.10 and 3.11, however.  So it isn't necessarily just a simple setuptools version requirement as it seems to depend on python version.  But some minimally agreeable version of setuptools can probably be find that accommodates the older python3 versions that are still technically supported versions.

It builds fine with py3.8-3.11 and setuptools 75.1.0.  I didn't bifurcate setuptools versions further to find the first good version after 63.1.0 and before 75.1.0.  That would be a little easier if I knew what to look for as I don't understand the error at this point.

    % python3.9 -m build --no-isolation --wheel
    * Getting build dependencies for wheel...
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 380, in <module>
        main()
      File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 364, in main
        json_out["return_val"] = hook(**hook_input["kwargs"])
      File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 141, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
        return self._get_build_requires(
      File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
        self.run_setup()
      File "/usr/local/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 1, in <module>
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 86, in setup
        _install_setup_requires(attrs)
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
        dist = MinimalDistribution(attrs)
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 57, in __init__
        super().__init__(filtered)
      File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 474, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 996, in <genexpr>
        eps = itertools.chain.from_iterable(
      File "/usr/local/lib/python3.9/site-packages/setuptools/_vendor/importlib_metadata/_itertools.py", line 16, in unique_everseen
        k = key(element)
    AttributeError: 'PathDistribution' object has no attribute '_normalized_name'
    
    ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel

**Comment by twm** [comment]
Hi @jhgit, thanks for the report!

I'm having trouble making sense of that traceback off the cuff, as Incremental doesn't have a `setup.py` file. In any case, old versions of setuptools are fraught so I think the pragmatic thing to do is drop the build-time setuptools dep. Hatchling is The Way.

**Comment by jhgit** [comment]
> Hi @jhgit, thanks for the report!
> 
> I'm having trouble making sense of that traceback off the cuff, as Incremental doesn't have a `setup.py` file.

FYI, that `setup.py` in the traceback comes from setuptools itself (it generates a stand-in setup.py if one does not exist).

lib/python3.9/site-packages/setuptools/build_meta.py has:

        def run_setup(self, setup_script='setup.py'):
            # Note that we can reuse our build directory between calls
            # Correctness comes first, then optimization later
            __file__ = setup_script
            __name__ = '__main__'

            with _open_setup_script(__file__) as f:
                code = f.read().replace(r'\r\n', r'\n')

            exec(compile(code, __file__, 'exec'), locals())

and...

    def _open_setup_script(setup_script):
        if not os.path.exists(setup_script):
            # Supply a default setup.py
            return io.StringIO(u"from setuptools import setup; setup()")

        return getattr(tokenize, 'open', open)(setup_script)


Thanks for the update.  That'll help some downstream packagers if now is a good time to make a new release.
