### ISSUE TITLE
Cannot make the incremental to run on Python 3.7.6 and Ubuntu 18.04.4

### ISSUE THREAD

**Issue by adamryczkowski** [twisted/incremental#52]
Trying to use incremental in my own project, but it failed. 
```
$ pip install -e mypkg
    ERROR: Command errored out with exit status 1:
     command: /home/adam/venv/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/adam/mypkg/setup.py'"'"'; __file__='"'"'/home/adam/mypkg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/adam/mypkg/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/adam/mypkg/setup.py", line 16, in <module>
        ''')
      File "/home/adam/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/adam/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.4.0/python-3.7.6-hf457cjp5qzyqa4avicanq2s5gs7tiyu/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/adam/venv/lib/python3.7/site-packages/setuptools/dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "/home/adam/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.4.0/python-3.7.6-hf457cjp5qzyqa4avicanq2s5gs7tiyu/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/adam/venv/lib/python3.7/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/home/adam/venv/lib/python3.7/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/home/adam/venv/lib/python3.7/site-packages/incremental/__init__.py", line 344, in _get_version
        dist.metadata.version = version_file["__version__"].public()
    AttributeError: 'str' object has no attribute 'public'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

`setup.py`:

```python
from setuptools import setup, find_packages
setup(name='loginspottercli',
      use_incremental=True,
      author="Adam Ryczkowski",
      packages=find_packages(),
      include_package_data=True,
      install_requires=[
      'requests',
      'click',
      'url_normalize',
      'tabulate'
      ],
      entry_points='''
      [console_scripts]
      mypkg=mypkg.mypkg:main
    ''')

```

and `_version.py`:

```python
from incremental import Version

__version__ = Version("mypkg", 0, 9, 3)
__all__ = ["__version__"]
```

**Comment by adiroiban** [comment]
I think that python 3.7 is by now not supported.
Also, `incremental` is not very actively maintained.
I am closing this as won't fix.
Feel free to comment and reopen if you think someone should work on this task.

Thanks for the report
